import React from 'react';

import styles from './AboutUs.module.scss';
import WhoWeAreIcon from '@/assets/icons/about-us/who-we-are.svg';
import MissionIcon from '@/assets/icons/about-us/mission.svg';
import AdvancedTechnologiesIcon from '@/assets/icons/about-us/advanced-tech.svg';
import UserFriendlyIcon from '@/assets/icons/about-us/user-friendly.svg';
import CustomizableOptionsIcon from '@/assets/icons/about-us/customizable-options.svg';
import CommitmentToExcellenceIcon from '@/assets/icons/about-us/commitment-to-excellence.svg';

const AboutUs: React.FC = () => {
  const whyChooseUsInfo = [
    {
      title: 'Advanced technologies',
      description: 'Our AI humanizer uses advanced algorithms to improve and adapt text accurately.',
      img: AdvancedTechnologiesIcon,
    },
    {
      title: 'User-friendly solutions',
      description: 'Simple and intuitive tools to ensure seamless integration into your workflow.',
      img: UserFriendlyIcon,
    },
    {
      title: 'Customizable options',
      description: 'Adapt text to specific tones, audiences, and contexts.',
      img: CustomizableOptionsIcon,
    },
    {
      title: 'Commitment to excellence',
      description: 'We strive to create AI-based solutions that make communication more meaningful.',
      img: CommitmentToExcellenceIcon,
    },
  ];

  return (
    <div className={styles['page-wrapper']}>
      <div className={styles.wrapper}>
        <div className={styles.container}>
          <div className={styles.body}>
            <p className={styles.title}>About us</p>
            <div className={styles.paragraphs}>
              <p className={styles.description}>
                At HumanizeMyAI, we believe in bridging the gap between artificial intelligence and human communication.
              </p>
              <p>
                Our mission is to transform robotic, impersonal text generated by artificial intelligence into language
                that feels authentic, understandable, and natural.
              </p>
            </div>
          </div>
          <div className={styles['info-container']}>
            <div className={styles['info-card']}>
              <WhoWeAreIcon width={48} height={48} />
              <p className={styles.title}>Who we are</p>
              <p className={styles.description}>
                We&apos;re a team of innovators, linguists, and AI enthusiasts who are passionate about improving the
                way people interact with technology. Our diverse backgrounds in artificial intelligence, natural
                language processing, and user experience design unite us in a common vision: to make AI interactions
                more human.
              </p>
              <p className={styles.description}>
                We work with professionals and organizations worldwide to solve AI-driven communication challenges, from
                startups to enterprises. By combining technical expertise with a deep understanding of human expression,
                we create tools that help companies and individuals connect with their audiences meaningfully.
              </p>
            </div>
            <div className={styles['info-card']}>
              <MissionIcon width={48} height={48} />
              <p className={styles.title}>Our Mission</p>
              <p className={styles.description}>
                Our mission is to humanize communication with artificial intelligence, making it accessible, empathetic,
                and effective. We strive to empower businesses, creators, and individuals by enabling AI to communicate
                clearly, understandably, and with a human tone. In doing so, we aim to improve how people interact with
                technology by fostering trust and meaningful participation in every conversation.
              </p>
              <p className={styles.description}>
                We recognize the growing role of artificial intelligence in communication, whether in chatbots, emails,
                or content creation. However, without the human touch, AI text often lacks the warmth, empathy, and
                clarity that real conversations require. This is where HumanizeMyAI comes in.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className={styles['why-choose-us-container']}>
        <p className={styles.title}>Why Choose Us</p>
        <div className={styles['why-choose-us-cards-container']}>
          {whyChooseUsInfo.map(({ title, description, img: Icon }) => (
            <div key={title} className={styles.card}>
              <Icon width={48} height={48} />
              <div className={styles['card-body']}>
                <p className={styles.title}>{title}</p>
                <p className={styles.description}>{description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
export default AboutUs;
