import React from 'react';

import styles from './AboutUs.module.scss';

const AboutUs: React.FC = () => {
  return (
    <div className={styles.wrapper}>
      <div className={styles.container}>
        <h1 className={styles.title}>About Us</h1>
        <div className={styles.description}>
          At HumanizeMyAI, we believe in bridging the gap between artificial intelligence and human communication. Our
          mission is to transform robotic, impersonal text generated by artificial intelligence into language that feels
          authentic, understandable, and natural.
        </div>
        <div className={styles.section}>
          <h2 className={styles['sub-title']}>Who we are</h2>
          <p>
            We&apos;re a team of innovators, linguists, and AI enthusiasts who are passionate about improving the way
            people interact with technology. Our diverse backgrounds in artificial intelligence, natural language
            processing, and user experience design unite us in a common vision: to make AI interactions more human.
          </p>
          <p>
            We work with professionals and organizations worldwide to solve AI-driven communication challenges, from
            startups to enterprises. By combining technical expertise with a deep understanding of human expression, we
            create tools that help companies and individuals connect with their audiences meaningfully.
          </p>
        </div>
        <div className={styles.section}>
          <h2 className={styles['sub-title']}>Our Mission</h2>
          <p>
            Our mission is to humanize communication with artificial intelligence, making it accessible, empathetic, and
            effective. We strive to empower businesses, creators, and individuals by enabling AI to communicate clearly,
            understandably, and with a human tone. In doing so, we aim to improve how people interact with technology by
            fostering trust and meaningful participation in every conversation.
          </p>
          <p>
            We recognize the growing role of artificial intelligence in communication, whether in chatbots, emails, or
            content creation. However, without the human touch, AI text often lacks the warmth, empathy, and clarity
            that real conversations require. This is where HumanizeMyAI comes in.
          </p>
        </div>
        <div className={styles.section}>
          <h2 className={styles['sub-title']}>Why Choose Us</h2>
          <ul className={styles.list}>
            <li>
              <p className={styles.label}>Advanced technologies</p>
              <p className={styles.text}>
                Our AI humanizer uses advanced algorithms to improve and adapt text accurately.
              </p>
            </li>
            <li>
              <p className={styles.label}>User-friendly solutions</p>
              <p className={styles.text}>
                Simple and intuitive tools to ensure seamless integration into your workflow.
              </p>
            </li>
            <li>
              <p className={styles.label}>Customizable options</p>
              <p className={styles.text}>Adapt text to specific tones, audiences, and contexts.</p>
            </li>
            <li>
              <p className={styles.label}>Commitment to excellence</p>
              <p className={styles.text}>
                We strive to create AI-based solutions that make communication more meaningful.
              </p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};
export default AboutUs;
