import Head from 'next/head';

import AboutUs from '@/templates/AboutUs/AboutUs';

import type { NextPage } from 'next';

const AboutUsPage: NextPage = () => {
  const pageTitle = `About Us — Abify`;
  const pageDescription = `At HumanizeMyAI, we believe in bridging the gap between artificial intelligence and human communication. Our mission is to transform robotic, impersonal text generated by artificial intelligence into language that feels authentic, understandable, and natural.`;
  const pageKeywords = `abify about, understandable ai, artificial intelligence, language processing`;

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content={pageDescription} />
        <meta name="keywords" content={pageKeywords} />
        <meta property="og:title" content={pageTitle} />
        <meta property="og:description" content={pageDescription} />
      </Head>

      <AboutUs />
    </>
  );
};

export default AboutUsPage;
