import { useState, useRef, useEffect } from 'react';
import ArrowDown from 'heroicons/20/solid/chevron-down.svg';
import ArrowUp from 'heroicons/20/solid/chevron-up.svg';

import styles from '@/templates/Home/FAQSection/Questions/Questions.module.scss';

const Questions = () => {
  const [openedQuestion, setOpenedQuestion] = useState<string | null>(null);

  interface Question {
    question: string;
    answer: string;
  }

  const FAQs: Question[] = [
    {
      question: 'What is Abify?',
      answer:
        'Abify is an advanced AI text humanizer that turns AI-generated text into natural, human-like writing. Our tool helps you bypass AI detectors and create unique, undetectable content that flows naturally.',
    },
    {
      question: 'Can Abify help me pass AI detectors?',
      answer:
        'Yes! Abify is specifically designed to rewrite AI-generated content in a way that makes it indistinguishable from human writing, ensuring it can bypass AI detection tools.',
    },
    {
      question: 'Will my content pass plagiarism checks?',
      answer:
        'Absolutely. Abify not only humanizes your AI content but also restructures it to ensure it’s original and can pass all major plagiarism checks.',
    },
    {
      question: 'What languages does Abify support?',
      answer:
        'Abify supports a wide range of languages, including English, Spanish, French, German, Chinese, Arabic, Hindi, Ukrainian, Japanese, Korean, Portuguese, and many more. Check out the full list above for all supported languages.',
    },
    {
      question: 'How does Abify work?',
      answer:
        'Simply upload your AI-generated text, choose your preferred tone and style, and let Abify humanize it. Within seconds, you’ll receive content that flows naturally and reads like it was written by a person.',
    },
    {
      question: 'Is my data safe with Abify?',
      answer:
        'Yes, we take privacy seriously. Abify ensures that all your data and content are handled securely, with no risk of exposure or sharing.',
    },
    {
      question: 'Can I use Abify for academic content?',
      answer:
        'Yes! Abify is ideal for students, researchers, and academics who want to rewrite AI-generated content in a way that feels human and passes plagiarism checks.',
    },
    {
      question: 'Is Abify fast?',
      answer:
        'Yes, Abify humanizes your content in a matter of seconds, making it perfect for those who need high-quality, human-like text quickly.',
    },
    {
      question: 'Can I customize the tone and style?',
      answer:
        'Absolutely. Abify allows you to choose from a variety of tones and styles, whether you need professional, casual, creative, or formal content.',
    },
    {
      question: 'Is Abify suitable for businesses and marketers?',
      answer:
        'Yes! Abify is perfect for businesses, marketers, and content creators looking to produce high-quality, natural-sounding text while bypassing AI detectors and maintaining SEO-friendly content.',
    },
    {
      question: 'Does Abify integrate with other platforms?',
      answer: 'Yes, you can export text in the desired format.',
    },
    {
      question: 'Does Abify work with text generated by ChatGPT?',
      answer: 'Absolutely! Abify is a powerful Chat GPT humanizer designed to refine any AI-generated text.',
    },
  ];

  const answerRefs = useRef<{ [key: string]: HTMLDivElement | null }>({});

  const handleClick = (question: string) => {
    if (openedQuestion === question) {
      setOpenedQuestion(null);
    } else {
      setOpenedQuestion(question);
    }
  };

  useEffect(() => {
    Object.keys(answerRefs.current).forEach(key => {
      const ref = answerRefs.current[key];
      if (ref) {
        const paragraph = ref.querySelector('p');
        if (openedQuestion === key) {
          ref.style.maxHeight = `${ref.scrollHeight + 50}px`;
          ref.style.paddingTop = '8px';
          if (paragraph) {
            paragraph.style.opacity = '1';
            paragraph.style.marginTop = '8px';
          }
        } else {
          ref.style.maxHeight = '0px';
          ref.style.paddingTop = '0px';
          if (paragraph) {
            paragraph.style.opacity = '0';
            paragraph.style.marginTop = '0px';
          }
        }
      }
    });
  }, [openedQuestion]);

  return (
    <div className={styles.questions}>
      {FAQs.map(faq => (
        <button
          type="button"
          key={faq.question}
          onClick={() => handleClick(faq.question)}
          className={`${styles.question} ${openedQuestion === faq.question ? styles.opened : ''}`}
        >
          <div className={styles.body}>
            <p>{faq.question}</p>
            {openedQuestion === faq.question ? (
              <ArrowUp width={24} height={24} />
            ) : (
              <ArrowDown width={24} height={24} />
            )}
          </div>
          <div
            className={styles.answer}
            ref={(el: HTMLDivElement | null) => {
              if (el) {
                answerRefs.current[faq.question] = el;
              }
            }}
          >
            <p>{faq.answer}</p>
          </div>
        </button>
      ))}
    </div>
  );
};

export default Questions;
